site_name: Column Masking in watsonx.data
site_description: Guide for implementing column masking in watsonx.data using IBM Knowledge Catalog (IKC)
site_url: ""

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: black
      accent: black
  font: false
  favicon: assets/favicon.png
  icon:
    logo: material/database-lock

extra_css:
  - https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - tables
  - attr_list
  - def_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - minify:
      minify_html: true

# Navigation
nav:
  - Home:
    - Overview: index.md
    - Quick Start: quick-start.md
  - Setup & Configuration:
    - Platform Connection: platform-connection.md
    - Metadata Import: metadata-import.md
  - Data Management:
    - Metadata Enrichment: metadata-enrichment.md
    - Projects: projects.md
    - Catalogs: catalogs.md
  - Security:
    - Rules and Policies: rules-policies.md